# Generated by Django 2.0.4 on 2018-05-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180507_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('New York City, NY', 'New York City, NY'), ('Normal, IL', 'Normal, IL'), ('Karachi, Pakistan', 'Karachi, Pakistan')], default='New York City, NY', max_length=30),
        ),
    ]
