# Generated by Django 2.0.4 on 2018-05-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('K', 'Khushi'), ('Z', 'Zain')], default='Z', max_length=2),
        ),
    ]
