# Generated by Django 2.0.4 on 2018-05-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Khushi', 'Khushi'), ('Zain', 'Zain')], default='Zain', max_length=10),
        ),
    ]
